### ISSUE TITLE
Finalize jupyterhub workflow

### ISSUE THREAD

**Issue by IDl0T** [AIwaffle/AIwaffle_Server1#5]
Only deploy courses with programming problems to jupyterhub

A new user should be able to work on the courses right after registration.

We are constantly adding new courses. Please take this into account.

Hide the `learning tools` from the user. You might need to modify some code

In the course "MNIST: Shallow, Deep, and CNN", please download the data from kaggle at the bottom of the page.

**Make sure to do tests**

**Comment by jimmy-zx** [comment]
Progress:
 - [x] OAuth2 Server
 - [ ] Deploy
 - [ ] Test
