### ISSUE TITLE
API request return empty body

### ISSUE THREAD

**Issue by AlienKevin** [AIwaffle/AIwaffle_Server1#7]
Posting the request
```
http://106.15.39.117:8080/auth/login
```
returns ERR_EMPTY_RESPONSE

Did the server root address change?

**Comment by jimmy-zx** [comment]
Maybe you need to update to `https://www.aiwaffle.com/`

**Comment by AlienKevin** [comment]
Yeah, I see the login page after updating the domain name. However, the responses are hard to use.
Log in success returns the full page html and log in failure returns another html. Can you return something like a json or provide an alternative request format for the frontend? An api I can think of looks like:
log in succeeds:
```json
{
"loggedIn" : true
}
```
log in fails:
```json
{
"loggedIn" : false,
"reason" : "Invalid username or password."
}
```
Best if you can distinguish between invalid username and invalid password.
register succeeds:
```json
{
"signedUp" : true
}
```
register fails:
```json
{
"signedUp" : false,
"reason" : "User admin is already registered."
}
```
Also, it seems that you don't accept json body for requests but uses form data. Is it possible to support json format throughout the api?

**Comment by jimmy-zx** [comment]
As the `/auth` path is related to "view", during the design I didn't consider about the API usage.

The authorization for API usage will be in `/api/auth`, and the original `/auth` path will be handled by the front end. Documentations will be updated.

**Comment by jimmy-zx** [comment]
Updated new API [documentation](https://github.com/AIwaffle/AIwaffle_Server1/blob/master/docs/api_auth.md)

**Comment by AlienKevin** [comment]
Thanks for the quick update! I will try the new api.

**Comment by AlienKevin** [comment]
`api/auth` log in and sign up works.
